version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      npm install
      # - command
  pre_build:
    commands:
      - /bin/sed -i "s/data_server_key:.*/data_server_key: '$DATA_SERVER_KEY'/g"  aurelia_project/environments/$ENVIRONMENT.js
  build:
    commands:
      - npm run test
      - npm run $ENV
      - rm -r node_modules
      # - command
  post_build:
    commands:
      - aws s3 sync . $TARGET_S3_BUCKET --sse
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**/*'
